### PR TITLE
fix(deps): updated all dependencies to fix CVEs

### PR DESCRIPTION
**Pull request by malmor**
This PR updates all dependencies and bumps the Go version to `1.19`.

This fixes multiple CVEs:
image

I also ran the linting - that's why a few smaller code changes are part of this PR.

### CODE REVIEW

**Comment by malmor** [comment]
Hey @manhtukhang,
I managed to compile a new version and it returned the expected `This binary is a plugin. These are not meant to be executed directly.`.

But I was not able to test this inside a Vault instance. Can you take a look at it?

We would love to see a new version being released with these changes! 🚀 
Looking forward to hearing from you.

Regards,
Malte

**Comment by malmor** [comment]
Hey @manhtukhang,
I fixed the pipeline failures with the latest commit and managed to get a dev environment up and running.

I compiled a new plugin version based on the latest commit and was able to successfully install and use the plugin.

As far as I can tell this new version should be working and ready for review/release.
Looking forward to hearing from you on this.

Regards,
Malte

**Comment by malmor** [comment]
Hey @manhtukhang,
any ideas on when you might have the time to take a look at this PR?

Kind Regards,
Malte

**Comment by manhtukhang** [comment]
Hi @malmor,

Sorry for the late response! I can merge this PR.

Thank you for your contribution!

**Pull request merged**
